all: cpulimit01 exit01

cpulimit01: ../src/evamik3_cpulimit01.c
	gcc -g -Wall -pedantic ../src/evamik3_cpulimit01.c -o cpulimit01

exit01: ../src/evamik3_exit01.c
	gcc -g -Wall -pedantic ../src/evamik3_exit01.c -o exit01